export const questionList = [
  "What are the must-see landmarks in Paris?",
  "How do I get to the Eiffel Tower?",
  "What are the opening hours of the Louvre Museum?",
  "Are there any guided tours of Notre-Dame Cathedral?",
  "What is the best time to visit Montmartre?",
  "How can I skip the lines at the Eiffel Tower?",
  "Where is the best spot for a photo of the Eiffel Tower?",
  "What are some hidden gems in Paris?",
  "Is it worth visiting the Catacombs of Paris?",
  "What are the best day trips from Paris?",
  "Can you recommend any free attractions in Paris?",
  "Are there any famous markets to visit in Paris?",
  "What is the best way to explore the Seine River?",
  "Are there any famous graves to visit in Père Lachaise Cemetery?",
  "What are the best museums in Paris besides the Louvre?",
  "Can you recommend a good viewpoint for the city skyline?",
  "What are the must-see churches in Paris?",
  "Where can I see Monet's paintings in Paris?",
  "What is the history of the Arc de Triomphe?",
  "Are there any restrictions for visiting the Palace of Versailles?",
  "Where can I find the Wall of Love (Mur des Je T’aime)?",
  "Is the Sainte-Chapelle worth visiting?",
  "What can I do at Jardin des Tuileries?",
  "Are there any walking tours available in the Marais district?",
  "What are the highlights of the Musée d'Orsay?",
  "Can you tell me about the Conciergerie and its history?",
  "What is the best way to visit Disneyland Paris?",
  "Are there any special events happening in Paris right now?",
  "How long should I spend at the Louvre?",
  "What are the best spots for a picnic in Paris?",
  "Is it possible to climb the towers of Notre-Dame?",
  "Can you recommend a good photography spot for Sacré-Cœur?",
  "What are the highlights of the Latin Quarter?",
  "Where can I learn about Paris’ history?",
  "Are there any boat tours on the Seine River?",
  "Can I visit the Opera Garnier?",
  "What can I do at the Luxembourg Gardens?",
  "What are the best food tours in Paris?",
  "Where can I find vintage shops in Paris?",
  "What is the best way to visit Montmartre without a guide?",
  "Can I take a day trip to Giverny to see Monet's gardens?",
  "Are there any castles near Paris to visit?",
  "How do I explore the Champs-Élysées?",
  "What can I see at the Musée de l'Orangerie?",
  "Is there a famous flea market in Paris?",
  "What are the best rooftop bars in Paris?",
  "Where can I find authentic Parisian pastries?",
  "What is the best time to visit the Eiffel Tower at night?",
  "Where can I experience Paris nightlife?",
  "What are the best neighborhoods to explore for local culture?",
  "Where can I buy tickets for a cabaret show like the Moulin Rouge?",
  "What are some good places to experience French cuisine?",
  "Can you recommend a Michelin-star restaurant in Paris?",
  "Where can I try authentic French wine?",
  "What are the best places to shop for souvenirs?",
  "Can you recommend a romantic activity for couples?",
  "What are the best parks for families with children?",
  "Are there any good spots for jogging in Paris?",
  "Where can I find local food markets?",
  "Can you recommend a Parisian chocolate shop?",
  "What is the best way to get to the airport from central Paris?",
  "How does the Paris Metro work?",
  "Can I rent a bike to explore the city?",
  "Are taxis or rideshares common in Paris?",
  "What is the best way to get around Paris?",
  "Are there any night buses in Paris?",
  "Where can I buy Metro tickets?",
  "Is it safe to walk around Paris at night?",
  "How do I use the Paris public transportation app?",
  "Can you recommend a good walking route along the Seine?",
  "Are there any Paris neighborhoods to avoid?",
  "Where can I find public restrooms in Paris?",
  "Are there any family-friendly activities in Paris?",
  "How do I say basic French phrases for travelers?",
  "Are there any cultural etiquette tips I should know?",
  "Can I drink tap water in Paris?",
  "What is the best way to handle money in Paris?",
  "Do most places accept credit cards?",
  "Are there any scams to watch out for?",
  "What is the best way to exchange currency?",
  "Where can I find a pharmacy in Paris?",
  "Can you recommend a good spot for watching the sunset?",
  "What are some popular festivals in Paris?",
  "How do I attend a fashion show in Paris?",
  "Are there any famous bakeries I should visit?",
  "What is the best season to visit Paris?",
  "How do I visit the Paris Catacombs?",
  "Are there any famous bridges in Paris?",
  "What are the rules for tipping in Paris?",
  "Where can I find a good jazz club?",
  "Can I take a cooking class in Paris?",
  "What are the best places for kids in Paris?",
  "Where can I find unique Paris souvenirs?",
  "What are the best books to read about Paris before my trip?",
  "Can you recommend a day itinerary for first-time visitors?",
  "What are the rules for photography in museums?",
  "Are there any famous libraries I can visit in Paris?",
  "What are the best food delivery apps in Paris?",
  "Can you recommend a local café with a view of the Eiffel Tower?",
  "What are the top Instagram spots in Paris?",
  "What is the best way to avoid tourist traps in Paris?",
];
